import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InitializeClient from "@/components/InitializeClient";
import AppStoreProvider from "@/store/AppStoreProvider";

import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Config } from "@/config/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  Config.locale = await getLocale();

  return (
    <html lang={Config.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitializeClient>
          <NextIntlClientProvider>
            <AppStoreProvider>{children}</AppStoreProvider>
          </NextIntlClientProvider>
        </InitializeClient>
      </body>
    </html>
  );
}
